typography_spectrum: 0.07654433348216116
color:
  brandColors:
    - '#00001c'
    - '#fafbdc'
    - '#584d53'
    - '#c2c0a7'
    - '#ead52e'
  brandStrength: 0.5909234441351146
  lightness: 0.7538543108385056
  saturation: 0.17836315371096134
  rhythmicContrast: 0.3822118933312595
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.03754217247478664
analytics:
  google: null
  facebook: null
  twitter: null
name: Kilowatts
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: null
purpose: []
